export const NEW_PRODUCT_ADDED = 'NEW_PRODUCT_ADDED';
export const NEW_BLOG_ADDED = 'NEW_BLOG_ADDED';
export const AUTHENTICATED = 'AUTHENTICATED';
export const UPDATE_ORDER_STATUS = 'UPDATE_ORDER_STATUS';
export const NEW_USER_REGISTERED = 'NEW_USER_REGISTERED';