// admin related events
export const NEW_PRODUCT_ADDED = 'NEW_PRODUCT_ADDED';
export const NEW_BLOG_ADDED = 'NEW_BLOG_ADDED';
export const AUTHENTICATED = 'AUTHENTICATED';
export const UPDATE_ORDER_STATUS = 'UPDATE_ORDER_STATUS';
export const NEW_USER_REGISTERED = 'NEW_USER_REGISTERED';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const CREATE_REVIEW_RATING = 'CREATE_REVIEW_RATING';

// authentication related events
export const LOGIN_EVENT = 'LOGIN_EVENT';
export const LOGOUT_EVENT = 'LOGOUT_EVENT';

// event related from blog.
export const NEW_COMMENT_ADDED = 'NEW_COMMENT_ADDED';
export const JOIN_ROOM_FOR_BLOG = "JOIN_ROOM_FOR_BLOG";
export const LEAVE_ROOM_FOR_BLOG = "LEAVE_ROOM_FOR_BLOG";
export const CREATE_REACTION_FOR_COMMENT = "CREATE_LIKE_FOR_COMMENT";
export const CREATE_REPLY_FOR_COMMENT = "CREATE_REPLY_FOR_COMMENT";
export const CREATE_REACTION_FOR_REPLY = "CREATE_REACTION_FOR_REPLY";
export const CREATE_REACTION_FOR_BLOG = "CREATE_REACTION_FOR_BLOG";